config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
resources "entries"

end

app/models/entry.rb
class Entry < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
def index
@entries = Entry.all
end
def show
  @entry = Entry.find(params["id"])
end
def new
end
def create
entry_params = params["entry"].permit("title", "contents")
  entry = Entry.create(entry_params)
  redirect_to(entry_path(entry))  

end
def edit
  @entry = Entry.find(params["id"])
end
def update
entry_params = params["entry"].permit("title", "contents")
  entry = Entry.find(params["id"])
  entry.update(entry_params)
  redirect_to(entry_path(entry))
end
  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
 
    redirect_to entries_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  @websites = [
      
      ["https://en.wikibooks.org/wiki/Ruby_Programming", "Wikibooks"],
      ["http://guides.rubyonrails.org", "Ruby on Rails Guides"],
	["http://www.twitter.com", "Twitter"]
    ]
@entries = Entry.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/entries/edit.html.erb
<%= form_for(@entry) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to this entry", entry_path(@entry)) %></p>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/index.html.erb
  <%= link_to("New entry", new_entry_path) %>
<br>
<h1>Today's date =><%= todaydate%></h1>
<% for entry in @entries %>

<h2><%= link_to(entry.title, entry_path(entry)) %></h2>
<% end %>

app/views/entries/new.html.erb
<%= form_for(Entry.new) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("contents") %></p>
  <p><%= form.text_area("contents") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back to all entries", entries_path) %></p>

app/views/entries/show.html.erb
<h2><%= @entry.title %></h2>
  <p><%= @entry.date %></p>
  <p><%= @entry.contents %></p>
<p><%= link_to("Edit this entry", edit_entry_path(@entry)) %></p>
<p><%= link_to 'Destroy', entry_path(@entry),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></p>
<br>
<p><%= link_to("Back", entries_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<!doctype html>
<html>
  <head>
    <title>My Little Webapp: Coding Is Magic</title>
    <meta charset="UTF-8" />
    <%= stylesheet_link_tag "/app/assets/stylesheets/style.css"%>

  </head>

<div>
  <h1>My favourite websites</h1>

<% for url, name in @websites %>
  <li><a href="<%= url %>"><%= name %></a></li>
<% end %>
  </div>
  <img src="http://railsgirls.com/images/rg-warsaw.png" />
  <body>
<% for entry in @entries %>
  <h2><%= entry.title %></h2>
    <p><%= entry.date %></p>
    <p><%= entry.contents %></p>
<% end %>
  </body>
</html>